-- MySQL Script generated by MySQL Workbench
-- Mon Nov 19 09:49:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema curriculum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema curriculum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `curriculum` DEFAULT CHARACTER SET utf8 ;
USE `curriculum` ;

-- -----------------------------------------------------
-- Table `curriculum`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculum`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `name_user` VARCHAR(45) NULL,
  `lastname_user` VARCHAR(45) NULL,
  `keypass_user` VARCHAR(45) NULL,
  `address_user` VARCHAR(45) NULL,
  `phone_user` VARCHAR(10) NULL,
  `mail_user` VARCHAR(45) NULL,
  `date_birth_user` DATETIME NULL,
  `obj_career_user` LONGTEXT NULL,
  `cv_title_user` VARCHAR(45) NULL,
  `handicap_user` VARCHAR(45) NULL,
  PRIMARY KEY (`id_users`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curriculum`.`exp_pro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculum`.`exp_pro` (
  `id_exp` INT NOT NULL AUTO_INCREMENT,
  `start_date_exp` DATETIME NULL,
  `end_date_exp` DATETIME NULL,
  `firm_name_exp` VARCHAR(45) NULL,
  `location_exp` VARCHAR(45) NULL,
  `job_exp` VARCHAR(45) NULL,
  `mission_exp` LONGTEXT NULL,
  `type_contract_exp` VARCHAR(45) NULL,
  `users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_exp`, `users_id_users`),
  INDEX `fk_exp_pro_users1_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_exp_pro_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `curriculum`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curriculum`.`trainings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculum`.`trainings` (
  `id_train` INT NOT NULL AUTO_INCREMENT,
  `start_date_train` DATETIME NULL,
  `end_date_train` DATETIME NULL,
  `school_train` VARCHAR(45) NULL,
  `location_train` VARCHAR(45) NULL,
  `title_train` VARCHAR(45) NULL,
  `dipl_name_train` VARCHAR(45) NULL,
  `dipl_validate_train` TINYINT NULL,
  `users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_train`, `users_id_users`),
  INDEX `fk_trainings_users1_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_trainings_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `curriculum`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curriculum`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculum`.`skills` (
  `id_skill` INT NOT NULL AUTO_INCREMENT,
  `title_skill` VARCHAR(45) NULL,
  `desc_skill` VARCHAR(45) NULL,
  `users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_skill`, `users_id_users`),
  INDEX `fk_skills_users1_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_skills_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `curriculum`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curriculum`.`activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculum`.`activities` (
  `id_act` INT NOT NULL AUTO_INCREMENT,
  `title_act` VARCHAR(45) NULL,
  `desc_act` VARCHAR(45) NULL,
  `users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_act`, `users_id_users`),
  INDEX `fk_activities_users_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_activities_users`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `curriculum`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curriculum`.`realisations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curriculum`.`realisations` (
  `id_rea` INT NOT NULL AUTO_INCREMENT,
  `title_rea` VARCHAR(45) NULL,
  `desc_rea` VARCHAR(45) NULL,
  `start_date_rea` DATETIME NULL,
  `end_date_rea` DATETIME NULL,
  `users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_rea`, `users_id_users`),
  INDEX `fk_realisations_users1_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_realisations_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `curriculum`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
